# Generated by Django 4.2.2 on 2023-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_solved",
            field=models.BooleanField(default=False),
        ),
    ]
